/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra48_2014_pnrs1_rtrk_taskmanager_NativeCalc */

#ifndef _Included_ra48_2014_pnrs1_rtrk_taskmanager_NativeCalc
#define _Included_ra48_2014_pnrs1_rtrk_taskmanager_NativeCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra48_2014_pnrs1_rtrk_taskmanager_NativeCalc
 * Method:    calculatePercentage
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_ra48_12014_pnrs1_rtrk_taskmanager_NativeCalc_calculatePercentage
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
